### ISSUE TITLE
Mailjet Adapter deliver_many return type is inconsistent

### ISSUE THREAD

**Issue by marcinkoziej** [swoosh/swoosh#732] opened 2022-12-01 09:30 UTC
Hi!

Thanks for this awesome library!

I had problems matching on error replies from Mailjet adapter, and to my surprise I discovered, that `deliver_many` will return different shape of data if there is only one email to send, vs if there are many emails to send.

We read emails to send from a queue and batch send them (with `deliver_many`)  so depending on the queue content sometimes we will send just a single email (one element list) or more.
This unfortunately affects the return data shape – not great.
Example:

`deliver_many([single_bad_email])`
```
{:error,
 {400,
  %{
    "Errors" => [
      %{
        "ErrorCode" => "mj-0013",
        "ErrorIdentifier" => "7c20b91c-a2b2-43ba-8be8-d46471f4d9c0",
        "ErrorMessage" => "\"marcin.@foobar.pl\" is an invalid email address.",
        "ErrorRelatedTo" => ["To[0].Email"],
        "StatusCode" => 400
      }
    ], 
    "Status" => "error"
  }}}
```

Type: `{atom(), {number(), map}}`

when I send one bad and one good email:
`deliver_many([bad_email, good_email])`

```
{:error,
 {400,
  [
    %{
      "Errors" => [
        %{
          "ErrorCode" => "mj-0013",
          "ErrorIdentifier" => "3dc47c3e-7719-416f-95c3-e20f286e92ca",
          "ErrorMessage" => "\"marcin.@cahoots.pl\" is an invalid email address.",
          "ErrorRelatedTo" => ["To[0].Email"],
          "StatusCode" => 400
        }
      ],
      "Status" => "error"
    },
    %{id: 288230391353929665}
  ]}}
```
Type: `{atom(), {number(), [map]}}`

I checked in the code to figure out if this is Swoosh or Mailjet introducing this inconsistency, and it _looks like_ it's actually Swoosh:

https://github.com/swoosh/swoosh/blob/69788f880ce6a2fb7a7ae6f92bfbc821391bf44d/lib/swoosh/adapters/mailjet.ex#L111

Can we do something about it?

I sure can handle both cases in my code – but for the sake of other Swoosh users, this is a really surprising and kinda wrong behavior - especially that developers will check mailjet API docs and assume the elixir return type will have a similar shape.

I know that fixing this would now break swoosh api :(  so not sure how to go about it. Do other adapters show similar behavior (returning single reply not in list for a single-element list input?)

Looking forward to Your answer,

best regards

Marcin

**Comment by princemaple** [comment] 2022-12-01 09:52
Yes that's definitely unexpected behavior that should be fixed - especially the fix will probably not be a breaking change, as it would eliminate an edge case for users. Still worth it even if it's slightly breaking, as it's never the intended behavior. I think we neglected the fact that `deliver_many` can take just 1 email, and wanted to be smart (😓) about DRY code..

Only 2 providers support deliver many emails in one go. Mailjet and Postmark. I don't think Postmark has this problem. The code didn't try to be smart there.

**Comment by princemaple** [comment] 2022-12-01 10:33
Would you be interested in giving the PR a go?

**Comment by marcinkoziej** [comment] 2022-12-01 11:15
Yes! 
Goal: always return a list in this case.

**Comment by marcinkoziej** [comment] 2022-12-01 11:16
Ah wait! You created the PR yourself!

**Comment by marcinkoziej** [comment] 2022-12-01 11:18
I see - you meant to check if it works for me - code looks good let my try it out

**Comment by marcinkoziej** [comment] 2022-12-01 11:36
works for me :)

**Comment by princemaple** [comment] 2022-12-01 11:44
Thanks!

**Closed** 2022-12-01 11:44 UTC
Labels: bug

**Comment by princemaple** [comment] 2022-12-01 11:50
Released v1.8.3

**Comment by marcinkoziej** [comment] 2022-12-01 12:29
@princemaple I think _swoosh_ is the sound you make squashing bugs. Thanks for acting so quick!

**Comment by princemaple** [comment] 2022-12-01 12:32
😆 I try
