### ISSUE TITLE
Trouble sending email over Gmail

### ISSUE THREAD

**Issue by sh4t4d33p** [swoosh/swoosh#191] opened 2018-01-05 11:05 UTC
I have created a basic email sending application. I have tested it locally using the mailbox preview server. However, when I change the configuration to send the email over Gmail, I get errors. 
1. When I use port 1025, the error is:- `{:error,
 {:retries_exceeded, {:network_failure, 'smtp.gmail.com', {:error, :timeout}}}}`.
2. When I use port 465, I get:- `{:error,
 {:retries_exceeded, {:network_failure, 'smtp.gmail.com', {:error, :closed}}}}`.
3. When I use port 587, I get:- `{:error, {:no_more_hosts, {:permanent_failure, 'smtp.gmail.com', :auth_failed}}}`.

My `config.exs` looks like this:-
`config :my_app, MyApp.Mailer,
    adapter: Swoosh.Adapters.SMTP,
    relay: "smtp.gmail.com",
    username: "some.name@gmail.com",
    password: "password",
    tls: :always,
    auth: :always,
    port: 587`
I enabled access through less secure apps in my Gmail account, but it's still not working. Could somebody tell me what the problem is?

**Comment by stevedomin** [comment] 2018-01-05 14:58
Hello @sh4t4d33p, sorry to hear you're having issues sending email with Swoosh/Gmail.

Do you have two-factor authentication enabled on this account by any chance? If that's the case you will need to generate an app specific password: https://support.google.com/accounts/answer/185833?hl=en

**Comment by sh4t4d33p** [comment] 2018-01-05 16:41
If you mean the 2-step verification which uses the password and a unique verification code, then I don't have it enabled.

**Comment by stevedomin** [comment] 2018-03-29 11:49
@sh4t4d33p I'm assuming this is no longer an issue and closing. Please reopen if that's not the case.

**Closed by stevedomin** 2018-03-29 11:49 UTC

**Comment by ugifractal** [comment] 2018-12-26 21:54
FYI: I am using mailman elixir and maybe same issue with swoosh, using mailman I got 

```
{:error, {:no_more_hosts, {:permanent_failure, 'smtp.gmail.com', :auth_failed}}}
```
but the error only happen on production, tried locally working good.

Then I changed the google account to the business account then working nicely.

So I think the problem is coming from SMTP account and (maybe) related to server IP address.

**Comment by mbaraa** [comment] 2023-08-07 22:29
Hello @stevedomin, the mentioned issue is still going on!

**Comment by princemaple** [comment] 2023-08-07 22:35
@mbaraa please file a new issue with your detailed error messages. Thanks!

**Comment by mbaraa** [comment] 2023-08-08 09:07
@princemaple it's already open in #785, I'll try the mentioned solution first I guess!
